language: android

os: linux
dist: trusty

jdk:
  - oraclejdk8

android:
  components:
    - build-tools-28.0.3
    - android-29
    - extra

notifications:
  email: false

branches:
  except:
    - gh-pages

script:
  - ./gradlew rxbilling:testReleaseUnitTest -i